// layouts/RootLayout.tsx
import type { Metadata } from "next";
import { Fredoka, Montserrat } from "next/font/google";
import Link from "next/link";
import NavLeft from "./components/NavLeft";
import "../globals.css";

const montserratSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const fredokaSans = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Panel de Administrador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${montserratSans} ${fredokaSans} antialiased`}>
      <div className="flex">
        {/* NavLeft */}
        <NavLeft />

        {/* Contenido principal */}
        <main className="flex-1 ml-64 p-6">
          {" "}
          {/* Añadido ml-64 para dar espacio al NavLeft */}
          <header className="bg-oliva-o flex flex-row items-center justify-between p-4 text-white">
            <h1 className="text-xl font-bold">Panel de Administrador</h1>
            <div className="flex flex-row gap-4">
              <Link href={"/administrador/"}>Inicio</Link>
              <Link href={"/administrador/agregar"}>
                Agregar sitio turístico
              </Link>
              <Link href={"/administrador/editar"}>Editar sitio turístico</Link>
            </div>
          </header>
          {/* Aquí se renderiza el contenido dinámico (children) */}
          {children}
        </main>
      </div>
    </div>
  );
}
