import type { Metadata } from "next";
import { Fredoka, Montserrat, Passion_One } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const montserratSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Variable correcta para Montserrat
  display: "swap",
});

const fredokaSans = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka", // Variable correcta para Fredoka
  display: "swap",
});

const passion_oneSans = Passion_One({
  subsets: ["latin"],
  variable: "--font-passion-one", // Variable correcta para Passion One
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${montserratSans.variable} ${fredokaSans.variable} ${passion_oneSans.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
